version: "3.9"

services:
  app:
    build: ./
    command: >
      /bin/bash -c "
      alembic upgrade head &&
      python bot.py"
    environment:
      BOT_TOKEN: ${BOT_TOKEN}
      DEBUG: ${DEBUG}
      PG_USERNAME: ${PG_USERNAME}
      PG_PASSWORD: ${PG_PASSWORD}
      PG_HOSTNAME: ${PG_HOSTNAME}
      PG_PORT: ${PG_PORT}
      PG_DB_NAME: ${PG_DB_NAME}
    depends_on:
      - postgres
    restart: unless-stopped

  postgres:
    image: postgres:16.1-bullseye
    container_name: postgres_container
    environment:
      POSTGRES_USER: ${PG_USERNAME}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
    driver: local